import random

# Daftar nama siswa
students = [
    "GHINOVA KLARISA IRAWADI", "YOSUA ARONGGEAR", "M. GIBRAN SANGADJI", "AURIL PUTRI AMANDA", "YASRIFAL FAWAZ",
    "AHMAD LUTFI", "BILI MAHESA", "MOCHAMAD WILDAN GRIANY", "MUHAMMAD ILHAM HANAFI", "ARISTYO RAHADIYAN",
    "SAMUEL TAMBUNAN", "HICKHAM AMWALA KOSWARA", "ANDARI DELA PUTRI", "RIZKI HIDAYATULLOH", "FELIX ANGGA RESKY",
    "LUTFI PERWIRA", "YOGIRA MANTODISAH PURBA", "NOUVAL M. ABDUL ROJAK", "MUHAMMAD FADHLAN PRATAMA", 
    "MUHAMAD PRABU RENADA F.", "REVAN FAJAR KUSTIAWAN", "BAKHITAH FIRJATULLAH", "RAHMA AMALIA", "RAFINA AZ ZAHRA",
    "FIDA NUJJIYA", "SANTANA ALFANDI YUSUF", "IRSA NURROHIM", "JIHAN KHAIRUNNISA", "DELISYA PRAMESTI FITRIYA", 
    "KAREN ANGGELIA PASARIBU", "MERRY GABRIELLA ANGEL SITORUS", "HILMI KHAIDAR NABILLA", "SITI RAUDATUL JANNAH FADILAH",
    "CHANDRA KIRANA IRAWAN", "MARTIN RIZKI WENDI SINURAT", "PASHA MUHAMMAD NASHWAN"
]

# Acak urutan siswa
random.shuffle(students)

# Bagi menjadi dua sesi
session_1 = students[:18]
session_2 = students[18:]

# Tampilkan hasil
print("Sesi 1:")
for i, student in enumerate(session_1, 1):
    print(f"{i}. {student}")

print("\nSesi 2:")
for i, student in enumerate(session_2, 1):
    print(f"{i}. {student}")
