import random

# Daftar nama siswa
students = [
    "MUHAMMAD RIFQI YUSUFI", "DINAN HAFIZHAN", "LUTHFIANDI RIZKI KURNIA", "MUHAMAD RIZKY", "ACHMAD BIMO RAHADIAN",
    "RADEN MUHAMMAD ARIIL AL-HAFIZH", "NIZAR ABDUL MALIK", "FADLI AHMAD FAHREZI", "RIZKY AQIL HIBATULLAH", "FADHAIL MUHAMMAD AL FALAQ",
    "LUQMANUL HAKIM", "DICKY FIRMANSYAH", "ABDULLAH GYBRAN RAHARJA", "TAQQY FAZHA GHAFARRA", "PUTRA KHAIRUL HAFIZD",
    "SHAFIRA APRILLIA", "NAKHWA GHINAYAH RAHADATUL AISY", "MUHAMMAD IQBAL PASHA AL FARABI", "MELVINA CHEDA RISMAYANTA", 
    "RIDA RAHMANIAH EL SYA'BANI", "IQBAL RAMADHAN", "MESA MELINDA", "AI RESTI SANIAH", "SYIFA LUTHFIYAH",
    "SONDANG ANJELINA NADEAK", "UJANG ISMAIL", "HIKAM HIKMATUL HUDA", "NAUFAL AHMAD FAUZAN", "MOH ILYAS", 
    "RIFAL SEPTIA HIDAYAT", "YUSUP KURNIAWAN", "MUHAMMAD ZIYAD", "NAURA MAHIRA HAYATUNUFUS", "DESTIANI MAHAPUTRI", 
    "RAMDHAN RULLYANSYAH", "DWI MELIANTI ISTIQOMAH", "MOCHAMMAD ILHAM FAUZAN", "RYAN HAPIDRI HERNOWO", "TIO NAATANAEL ZAGOTO", 
    "SANTANA ALFANDI YUSUF"
]

# Acak urutan siswa
random.shuffle(students)

# Bagi menjadi dua sesi
session_1 = students[:20]
session_2 = students[20:]

# Tampilkan hasil
print("Sesi 1:")
for i, student in enumerate(session_1, 1):
    print(f"{i}. {student}")

print("\nSesi 2:")
for i, student in enumerate(session_2, 1):
    print(f"{i}. {student}")